version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.0.0
    - 1.11.0
    - 1.12.0
  - dependency-name: rubocop-rspec
    versions:
    - 1.44.1
