# Within GOV.UK we use Capybara test method syntax of feature,
# scenario. We don't want this outside of feature or system specs though.
RSpec/Dialect:
  Exclude:
    - 'spec/features/**/*.rb'
    - 'spec/system/**/*.rb'
