require: rubocop-capybara

# Within GOV.UK we use Capybara test method syntax of feature,
# scenario. 
Capybara:
  Enabled: true

# We don't want this cop outside of feature or system specs though.
RSpec/Dialect:
  Exclude:
    - 'spec/features/**/*.rb'
    - 'spec/system/**/*.rb'
