on:
  workflow_dispatch: {}
  schedule:
    - cron: '00 13 * * 2'

jobs:
  autorelease:
    uses: alphagov/govuk-infrastructure/.github/workflows/autorelease-rubygem.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
